In [12]:
import pandas as pd

persone = [
   {
        'nome': 'Mario', # chiave: nome, valore: Marco
        'cognome': 'Ricci',
        'eta': 30,
        'citta': 'Milano',
        'codice_fiscale': 'MRI7894DH45O1P',
        'professione': 'Ingegnere'
    },
    {
        "nome": "Rudy",
        "cognome": "Botosso",
        "eta": 54,
        "citta": "Biella",
        "codice fiscale": "BTTRDY71L15A859E",
        "professione": "Informatico"
    },
    {
        "nome": "Marco",
        "cognome": "Secci",
        "eta": 54,
        "citta": "San Donà di Piave",
        "codice fiscale": "SCCMRC71P22H823A",
        "professione": "Disoccupato"
    },
    {
        'nome':'Andrea',
        'cognome':'Romano',
        'eta': 36,
        'citta': 'Ripatransone',
        'codice_fiscale': 'RNINFEINFIEN',
        'professione': 'Studente'
    },
    {
            'nome': 'Saverio', 
            'cognome': 'Carulli',
            'eta': 34,
            'citta': 'Spinazzola',
            'codice_fiscale': 'CRLSVR92H24O1P',
            'professione': 'Disoccupato'
    },
    {
        'nome': 'Giulia', 
        'cognome': 'Pierro',
        'eta': 25,
        'citta': 'Latina',
        'codice_fiscale': 'PRRGLI7894DH45O1P',
        'professione': 'Studente'
    },
    {
        'nome': 'Fabrice',
        'cognome': 'Cheick',
        'eta': 51,
        'citta': 'Ferrara',
        'codice_fiscale': 'CHKFRC75Z20H231G',      
        'professione': 'Pastore'
    },
    {
        'nome': 'Laura',
        'cognome': 'Ricordi',
        'eta': 33,
        'citta': 'Alessandria',
        'codicefiscale':  'chi lo sa?',
        'professione': 'speriamo hr data analyst'
    },
    {
        'nome': 'Luigia',
        'cognome': 'Valente',
        'eta': 32,
        'citta': 'Avellino',
        'codice_fiscale': 'VLNLGU93R64A783K',
        'professione': 'Receptionist'
    },
    {
        'nome': 'Teresa',
        'cognome': 'Balsamo',
        'eta': 25,
        'citta': 'Roma', 
        'codice_fiscale': 'BLSTRS00H48A024P',
        'professione': 'in_cerca'   
    }
]

df = pd.DataFrame(persone)
df
print(df)

      nome  cognome  eta              citta     codice_fiscale  \
0    Mario    Ricci   30             Milano     MRI7894DH45O1P
1     Rudy  Botosso   54             Biella                NaN
2    Marco    Secci   54  San Donà di Piave                NaN
3   Andrea   Romano   36       Ripatransone       RNINFEINFIEN
4  Saverio  Carulli   34         Spinazzola     CRLSVR92H24O1P
5   Giulia   Pierro   25             Latina  PRRGLI7894DH45O1P
6  Fabrice   Cheick   51            Ferrara   CHKFRC75Z20H231G
7    Laura  Ricordi   33        Alessandria                NaN
8   Luigia  Valente   32           Avellino   VLNLGU93R64A783K
9   Teresa  Balsamo   25               Roma   BLSTRS00H48A024P

                professione    codice fiscale codicefiscale
0                 Ingegnere               NaN           NaN
1               Informatico  BTTRDY71L15A859E           NaN
2               Disoccupato  SCCMRC71P22H823A           NaN
3                  Studente               NaN           NaN
4               Disoccupato               NaN           NaN
5                  Studente               NaN           NaN
6                   Pastore               NaN           NaN
7  speriamo hr data analyst               NaN    chi lo sa?
8              Receptionist               NaN           NaN
9                  in_cerca               NaN           NaN

In [ ]:
# creazione del dataframe 
studenti = {
    "nome": ["Mario", "Rudy", "Marco"],
    "cognome": ["Ricci", "Botosso", "Secci"],
    "eta": [30, 54, 54],
    "citta": ["Milano", "Biella", "Roma"],
    "voto": [8, 9, 7]
}

#chiama pandas e crea un dataframe a partire da un dizionario
df = pd.DataFrame(studenti)
df

<br/>
<h1>prova<h1/>

# prova
## prova 2
### prova 3

In [18]:
# Creazione del dataframe(studenti) = dataset(tabella) 
studenti = {
    "nome": ["Mario", "Rudy", "Marco"],
    "cognome": ["Ricci", "Botosso", "Secci"],
    "eta": [30, 54, 54],
    "citta": ["Milano", "Biella", "San Donà di Piave"],
    "voto": [8, 9, 7]
}

# chiama pandas e crea un dataframe a partire dal dizionario studenti
df = pd.DataFrame(studenti)
df # stampa il dataframe(tipo tabella) con i dati degli studenti
print(df) # stampa il dataframe(tipo tabella in formato csv)

    nome  cognome  eta              citta  voto
0  Mario    Ricci   30             Milano     8
1   Rudy  Botosso   54             Biella     9
2  Marco    Secci   54  San Donà di Piave     7

### Stampa la prima riga della tabella

In [ ]:
df.head(3) #mostra le prime 3 righe del dataframe(tabella). Uguale a select top 3 from studenti in sql

    nome  cognome  eta              citta  voto
0  Mario    Ricci   30             Milano     8
1   Rudy  Botosso   54             Biella     9
2  Marco    Secci   54  San Donà di Piave     7

<h4> La funzione <strong>info()</strong> restituisce l'informazione del <i>dataframe</i></h4>

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   nome     3 non-null      str
 1   cognome  3 non-null      str
 2   eta      3 non-null      int64
 3   citta    3 non-null      str
 4   voto     3 non-null      int64
dtypes: int64(2), str(3)
memory usage: 252.0 bytes

- describe() <strong>restituisce le statistiche descrittive del <i>Dataframe</i></strong>

|Definizione | Valore   |
|------------|----------| 
|count       |  conta   |
|mean	     |  media   |
|min	     |  minimo  |
|max	     |  massimo |

In [22]:
df.describe()

             eta  voto
count   3.000000   3.0
mean   46.000000   8.0
std    13.856406   1.0
min    30.000000   7.0
25%    42.000000   7.5
50%    54.000000   8.0
75%    54.000000   8.5
max    54.000000   9.0

#### <i>df['nome']</i> resituisce lista dei nomi

In [25]:
df['nome']

0    Mario
1     Rudy
2    Marco
Name: nome, dtype: str

 - restituisce lista nomi e voti

In [30]:
df[['nome', 'cognome','voto']]

    nome  cognome  voto
0  Mario    Ricci     8
1   Rudy  Botosso     9
2  Marco    Secci     7